### ISSUE TITLE
(p Program) toType 将Go的原始类型转换为LLVM类型

### ISSUE THREAD

**Issue by luoliwoshang** [luoliwoshang/llgo#22]
#5 
- [x]  对于基础类型，返回对应的基础类型的LLVM值
https://github.com/luoliwoshang/llgo/blob/4f21915f35e498c46ff4899c3b061c42aeac9d30/ssa/type.go#L294-L329
- [x] 对于指针类型`types.Pointer`，获得指针指向的类型的LLVM类型 #22 ，并拼接为一个LLVM类型
- [ ] 接口类型
- [ ] 切片类型
- [ ] Map类型
- [x] 结构体类型：将结构体的每一项都转换获取LLVM类型 #22，据此创建一个LLVM类型返回
- [ ] *types.Named
- [ ] *types.Signature
- [ ] *types.Tuple 元组
- [x] *types.Array 数组 将每一项都处理为LLVM类型 #22 ，返回LLVM类型
